version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - apt-get update -y
      - apt-get install maven -y

  pre_build:
    commands:
      - echo Compile the source code.
      - mvn -Pprod clean -DskipTests

  build:
    commands:
      - echo Build the Spring Boot Application
      - mvn clean install -Dspring.profiles.active=prod

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - cleanup_before_install.sh
    - start_application.sh
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
